TTS/tts/utils/languages.py
Noticed this when testing the mixed-language TTS:
Previously, running `LanguageManager.init_from_config(config)` would never use the `language_ids_file` if that field is present because it was overwritten in the next line with a new manager that manually parses languages from the datasets in the config. Now that is only used as a fallback.
=> fix(LanguageManager): allow initialisation from config with language ids file

TTS/tts/utils/text/phonemizers/espeak_wrapper.py, pyproject.toml, tests/tts_tests/test_losses.py
Fixes https://github.com/coqui-ai/TTS/issues/2728.
Previously, error messages from espeak were treated as normal output and also
converted to tokens. This captures and logs them separately.
The second commit addresses lint suggestions from ruff.
=> fix(espeak_wrapper): capture stderr separately

TTS/tts/layers/bark/inference_funcs.py, TTS/tts/models/bark.py
Fixes https://github.com/coqui-ai/TTS/issues/2795
=> fix(bark): add missing argument for load_voice() 

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/PR_TEMPLATE.md, TTS/encoder/utils/prepare_voxceleb.py, TTS/server/server.py
Running the server didn't show any output because `setup_logger()` was not used as in other similar executables. Addresses #24, but does not yet fix the underlying issue there.
=> fix(server): ensure logging output gets actually shown

TTS/tts/utils/text/phonemizers/espeak_wrapper.py, tests/text_tests/test_phonemizer.py
- Fixes #24 by updating the Espeak wrapper code to much simpler `subprocess.run` interface
- Fixes https://github.com/coqui-ai/TTS/discussions/3761 by letting `Espeak.phonemize()` read input from a file to avoid character encoding issues in shell arguments
=> Fix Espeak issues on Windows

README.md, TTS/__init__.py, docs/source/conf.py, pyproject.toml
Work around #31 (until XTTS streaming code is updated) by restricting `transformers` to versions below 4.41.0.
Also restore the `TTS.__version__` attribute, which is used by the `TTS/bin/collect_env_info.py` script with which users print
version information for bug reports, so that old versions of the script still work.
=> Fix XTTS streaming

README.md, TTS/bin/compute_attention_masks.py, TTS/bin/compute_embeddings.py, TTS/bin/eval_encoder.py, TTS/bin/extract_tts_spectrograms.py, TTS/bin/remove_silence_using_vad.py, TTS/bin/synthesize.py, TTS/encoder/README.md, TTS/server/README.md, TTS/tts/models/xtts.py, TTS/utils/generic_utils.py, docs/source/docker_images.md, docs/source/models/bark.md, docs/source/models/tortoise.md, docs/source/models/xtts.md, recipes/ljspeech/fast_pitch/train_fast_pitch.py, recipes/ljspeech/fast_speech/train_fast_speech.py, recipes/ljspeech/fastspeech2/train_fastspeech2.py, tests/zoo_tests/test_models.py
Previously, e.g. `--use_cuda false` would actually set use_cuda=True as reported in https://github.com/coqui-ai/TTS/discussions/3762
Also fix a call to `datetime.datetime.now()`
=> Improve CLI handling of boolean arguments

TTS/vc/models/freevc.py
Use the specified device for pretrained speaker encoder Fixes coqui-ai#3787
=> Use the specified device for pretrained speaker encoder

TTS/tts/layers/xtts/stream_generator.py, pyproject.toml
Fixes #31. Tested by confirming the [XTTS streaming code](https://coqui-tts.readthedocs.io/en/latest/models/xtts.html#streaming-manually) now works with transformers>=4.41
The streaming implementation closely follows the [`GenerationMixin.generate()` function](https://github.com/huggingface/transformers/blob/eed9ed679878ada2f6d2eefccdbda368cabc88b1/src/transformers/generation/utils.py#L1532), so I just updated it in line with upstream changes.
=> Fix XTTS streaming for transformers update

TTS/bin/train_encoder.py, TTS/encoder/utils/visual.py, pyproject.toml
Except for notebooks, it's only used to show embedding plots during speaker encoder training, in which case a warning is now shown to install it.
=> build: move umap-learn into optional notebook dependencies

TTS/tts/datasets/dataset.py
Avoids hard failures when computing audio file lengths. Broken files are logged with a warning instead.
=> Skip audio files that can't be decoded

pyproject.toml
- Update `gruut` to version 2.4.0 with Numpy 2 and networkx 3 (fixing #55, fixing #68) support.
- ~~[librosa](https://github.com/librosa/librosa/issues/1831)/[soxr](https://github.com/dofuuz/python-soxr/issues/28) are still in the process of being updated, but the soxr 0.4.0b1 prerelease works.~~ Edit: works fine now with soxr 0.4.0
- [spacy](https://github.com/explosion/spaCy/issues/13528)/[thinc](https://github.com/explosion/thinc/issues/939) are not built with Numpy 2 support yet, so add back an upper bound.
- Limit `transformers` to versions 4.42.* as temporary workaround for #65
=> Numpy 2 support (gruut, soxr, spacy)

docs/source/models/tacotron1-2.md
I found that some links in the documentation link to the wrong papers.
(Moved from: https://github.com/coqui-ai/TTS/pull/3963)
=> Fix wrong references in documentation

pyproject.toml
It still installs Numpy<2 for now because Spacy although built with Numpy 2 support still depends on an older `thinc` version: https://github.com/explosion/spaCy/issues/13607 Should work automatically in future releases.
=> Enable Numpy 2 support after Spacy 3.8 release

TTS/tts/utils/text/cleaners.py, tests/text_tests/test_text_cleaners.py
There are duplications in the cleaners, should the normalizer be added inside the other cleaners, or be applied to all text? 
https://github.com/idiap/coqui-ai-TTS/blob/dev/TTS/tts/utils/text/tokenizer.py#L110
/Closes #63
=> Add normalizer type C to text cleaners

pyproject.toml
Fixing versions of dependencies in the pyproject.toml.
Probably some version restrictions could be lowered.
dependencies = [
#...
"cython==3.0.11", # Added exact version
"spacy[ja]==3.7.5", # Added exact version
"soxr==0.4.0", # Added exact version
"scikit-learn==1.5.1", # Added exact version
"contourpy==1.2.1", # Added exact version
]
Fixes #91
=> Potential fix for #90, #91

.github/workflows/pypi-release.yml, pyproject.toml
[cibuildwheel](https://github.com/pypa/cibuildwheel) allows building wheels for different platforms, so that we can now also provide Mac and Windows wheels.
=> ci(release): switch to cibuildwheel

TTS/tts/layers/xtts/stream_generator.py, pyproject.toml
Copy of #98, authored by @JohnnyStreet (editing not enabled for that PR). I fixed the style check and had to add some constraints so that the dependency resolution with uv works (to avoid https://github.com/astral-sh/uv/issues/6281). I checked locally that the streaming XTTS inference works with transformers 4.43, 4.44 and 4.45.
Fixes #65
=> Add compatibility with transformers>=4.43

TTS/tts/layers/tortoise/autoregressive.py, TTS/tts/layers/xtts/gpt.py, TTS/tts/layers/xtts/gpt_inference.py, TTS/tts/models/xtts.py
Sets the attention mask in Tortoise and XTTS to avoid the following warning: ```The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.```
Also address other warnings during XTTS inference to be ready for future changes in the transformers library.
Obsoletes #106
=> fix(gpt): set attention mask and address other warnings

TTS/encoder/models/lstm.py, TTS/tts/layers/bark/load_model.py, TTS/tts/layers/tortoise/diffusion_decoder.py, TTS/tts/models/delightful_tts.py, TTS/tts/models/forward_tts.py, TTS/tts/models/glow_tts.py, TTS/tts/models/tacotron.py, TTS/tts/models/tacotron2.py, TTS/tts/models/vits.py
> torch.cuda.amp.autocast(args...) and torch.cpu.amp.autocast(args...) will be deprecated. Please use torch.autocast("cuda", args...) or torch.autocast("cpu", args...) instead.
https://pytorch.org/docs/stable/amp.html
=> refactor: handle deprecation of torch.cuda.amp.autocast

.github/actions/setup-uv/action.yml, .github/workflows/integration-tests.yml, .github/workflows/pypi-release.yml, .github/workflows/style_check.yml, .github/workflows/tests.yml, TTS/.models.json, TTS/demos/xtts_ft_demo/utils/gpt_train.py, TTS/tts/layers/tortoise/arch_utils.py, TTS/tts/layers/xtts/trainer/gpt_trainer.py, TTS/utils/manage.py, pyproject.toml, recipes/ljspeech/xtts_v1/train_gpt_xtts.py, recipes/ljspeech/xtts_v2/train_gpt_xtts.py
The `scarf.sh`-redirect URLs were only needed for Coqui to collect statistics. It's clearer to show the original URLs, which can be obtained with e.g. `wget --spider --max-redirect=1 https://coqui.gateway.scarf.sh/hf/bark/coarse_2.pt`
In CI:
- deduplicate by moving `setup-uv` into a composite action
- run the slower integration tests only for the lowest and highest supported Python version to reduce the number of CI checks and total running time
=> Show original model URLs

Dockerfile
This PR fixes the dockerfile building on Mac M1
=> Add Support for building Docker on arm64

TTS/tts/datasets/__init__.py, TTS/tts/models/xtts.py, TTS/utils/audio/numpy_transforms.py, TTS/utils/audio/processor.py
Audio is now automatically converted to mono (using librosa, which averages all channels) and a warning is shown for non-mono files. Fixes #153
I also added more helpful error messages for these common issues:
- passing a custom formatter name to the dataset config
- loading XTTS checkpoint from a folder that doesn't contain a vocab.json file
I refactored the audio processing code a bit to deduplicate, improve type hints and fix lint issues.
=> Automatically convert audio to mono, add more helpful error messages

TTS/demos/xtts_ft_demo/utils/gpt_train.py, TTS/tts/layers/xtts/trainer/gpt_trainer.py, TTS/tts/models/xtts.py, recipes/ljspeech/xtts_v1/train_gpt_xtts.py, recipes/ljspeech/xtts_v2/train_gpt_xtts.py, tests/xtts_tests/test_xtts_gpt_train.py, tests/xtts_tests/test_xtts_v2-0_gpt_train.py
The XTTS `load_checkpoint()` method accepts both `checkpoint_dir` and `checkpoint_path` arguments, in that order. It's easy to call it with `load_checkpoint("model.pth")` by mistake. Now a clear error message is shown in that case, suggesting to use `load_checkpoint(checkpoint_path="model.pth")` instead.
=> fix(xtts): clearer error message when file given to checkpoint_dir

TTS/api.py, TTS/bin/synthesize.py, docs/source/models/bark.md, docs/source/models/xtts.md, tests/zoo_tests/test_models.py
This PR aligns the Python API more closely with what is available via the CLI. Previously pretrained TTS models could only be used with their default vocoder.
For example, this uses `vocoder_models/en/ljspeech/hifigan_v2`
```python
from TTS.api import TTS
tts = TTS("tts_models/en/ljspeech/fast_pitch")
_ = tts.tts("hello")
```
Now you can also pass a different pretrained vocoder name
```python
tts = TTS(
"tts_models/en/ljspeech/fast_pitch",
vocoder_name="vocoder_models/en/ljspeech/multiband-melgan"
)
_ = tts.tts("hello")
```
Combining a pretrained TTS model with a local vocoder and vice-versa or passing a custom speaker encoder is also possible now.
I then refactored the CLI to use the Python API internally, so that everything goes through the same pipeline for consistency.
=> Expand Python API capabilities

TTS/utils/manage.py, docs/source/faq.md
Users regularly ask where models are stored, this will print the location at the end when running `tts --list_models`
=> feat(manager): print download location when listing models

TTS/bin/compute_attention_masks.py, TTS/bin/compute_embeddings.py, TTS/bin/compute_statistics.py, TTS/bin/eval_encoder.py, TTS/bin/extract_tts_spectrograms.py, TTS/bin/find_unique_chars.py, TTS/bin/find_unique_phonemes.py, TTS/bin/remove_silence_using_vad.py, TTS/bin/synthesize.py, TTS/bin/train_encoder.py, TTS/bin/train_tts.py, TTS/bin/train_vocoder.py, TTS/bin/tune_wavegrad.py, TTS/encoder/utils/prepare_voxceleb.py, TTS/server/server.py, TTS/utils/generic_utils.py, docs/source/models/xtts.md
Send logs from the CLI tools in `TTS.bin` to `stdout`, so that the outputs are available for further downstream processing:
```python
tts --list_models | grep vits
```
For `TTS/bin/synthesize.py`, if `--pipe_out` is set, log to `stderr` instead because
then only the output audio stream should be on `stdout`, e.g. to pipe it to `aplay`.
Fixes #214
=> fix(bin): log to stdout in cli tools

TTS/tts/layers/xtts/tokenizer.py, pyproject.toml
The `num2words` library fixed their non-standard czech code so the fix to change `cs` to `cz` is no longer needed and actually causes an exception.
The fix was introduced to the `num2words` library in this PR: https://github.com/savoirfairelinux/num2words/pull/587
Which was released in this version: https://github.com/savoirfairelinux/num2words/releases/tag/v0.5.14
Should resolve https://github.com/idiap/coqui-ai-TTS/issues/236
=> Fix num2words call using non-standard lang code

TTS/tts/utils/text/english/number_norm.py, tests/text_tests/test_text_cleaners.py
When trying to convert numbers to words in [coqui-ai-TTS/TTS/tts/utils/text/english/number_norm.py](https://github.com/idiap/coqui-ai-TTS/blob/dev/TTS/tts/utils/text/english/number_norm.py), numbers with more than 36 digits will cause inflect to throw `inflect.NumOutOfRangeError` crashing the app.
This script will reproduce the issue:
```python
from TTS.api import TTS
tts = TTS("tts_models/en/ljspeech/tacotron2-DDC").to("cuda")
big_number = "1" + "0" * 36  # this will not work
text = f"The number is {big_number}"
tts.tts_to_file(
text=text,
file_path="output.wav",
)
```
The solution is to read out numbers with more than 36 digits one digit at a time. This replicates how a human speaker might handle this. For example reading out digits of pi.
I have added two tests to verify this change. …
=> Converting large numbers to text causes crash

TTS/tts/layers/bark/load_model.py, TTS/tts/models/bark.py
The config for Bark that Coqui downloads from https://huggingface.co/erogol/bark/tree/main contains some incorrect links/paths that can lead to errors in case of failed downloads. This patches up these links accordingly.
Fixes https://github.com/coqui-ai/TTS/issues/2781
Fixes https://github.com/coqui-ai/TTS/issues/3064
Fixes https://github.com/coqui-ai/TTS/issues/3608
Fixes https://github.com/coqui-ai/TTS/issues/3804
Fixes https://github.com/coqui-ai/TTS/issues/4116
Fixes https://github.com/coqui-ai/TTS/issues/4065
=> fix(bark): handle broken paths in config

TTS/vc/models/openvoice.py
Wrong dimension was used previously. Fixes #234
=> fix(openvoice): correctly set utterance length

TTS/tts/models/vits.py, pyproject.toml, tests/zoo_tests/test_models.py
Since 0.25.2 Coqui renames most model file names to `model.pth` to not have to add special cases for every name. But Fairseq models were already a special case and expected `G_100000.pth`. Now both `G_100000.pth` and `model.pth` are accepted. I also added two Fairseq models to the zoo tests to catch such issues earlier in the future.
Fixes #263
=> fix(fairseq): handle change of model file name

TTS/server/server.py, TTS/server/templates/index.html, TTS/tts/models/xtts.py
It needs to be tested before merging.
Closes #254
=> Added speaker_wav parameter to the server

TTS/api.py
XTTS accepts a `speed` parameter, but that was previously captured in the API which prevented it from being passed through. Removing the non-functional `speed` parameter from the API lets it pass via `kwargs` to models that support it.
```python
from TTS.api import TTS
xtts = TTS("tts_models/multilingual/multi-dataset/xtts_v2")
xtts.tts_to_file("Hello, this is a short test text to test TTS.", language="en", speaker="Ana Florence", speed=2.0)
```
Obsoletes #239
=> feat(api): support setting speed

TTS/tts/layers/xtts/trainer/gpt_trainer.py
By overwriting `model_args` in `GPTTrainerConfig` based on the suggestion in https://github.com/coqui-ai/TTS/issues/3510#issuecomment-1885760991.
Fixes https://github.com/coqui-ai/TTS/issues/3131
Fixes https://github.com/coqui-ai/TTS/issues/3510
Obsoletes #79
=> Support use of `--continue_path` to resume XTTS training

.github/workflows/docker.yaml, .github/workflows/pypi-release.yml, .github/workflows/style_check.yml, .github/workflows/tests.yml, pyproject.toml
Now your workflows won't auto-run if the only files changed consist of these
```bash
CITATION.cff
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.txt
README.md
```
To save resources, as those files... don't break the code base ever
:)
=> Added paths-ignore in workflows

TTS/tts/models/forward_tts.py
When training a multi-speaker ForwardTTS model with speaker embeddings enabled, the training loop fails with the following error:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
This happens because the speaker ID tensor g (from the batch) is on the CPU, while the model’s emb_g embedding layer is on the GPU.
This PR fixes the device mismatch by explicitly moving g to the same device as the input tensor x before calling self.emb_g(g) in _forward_encoder.
=> fix(forward_tts): ensure tensor 'g' is on the same device as 'x'

Dockerfile, TTS/tts/layers/xtts/tokenizer.py, docs/source/marytts.md, docs/source/models/xtts.md, docs/source/server.md, pyproject.toml
Spacy will likely be very slow to support Python 3.13, so it's better to let users install it themselves if they need it. Coqui anyway only used it for text splitting in XTTS, which is already disabled by default.
=> Remove Spacy dependency

TTS/tts/utils/helpers.py
This value shouldn't be converted to a Python `int` because then it is a constant when exported to onnx, see:
```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect.
We can't record the data flow of Python values, so this value will be treated as a constant in the
future. This means that the trace might not generalize to other inputs!
```
Fixes #315
=> fix: don't convert to int to avoid constant value in onnx exports

TTS/__init__.py, pyproject.toml
Hello guys, 
First, thanks a lot for maintaining coqui-tts, you all are open source heros!!
I've noticed you removed compatibiliy with numpy 1 in the 0.26.1. There are two main problems with that
1. Going from `numpy>=1.25.2,<2.0` to `numpy>=2` is a breaking change that ideally should be avoided in a patch release.
2. Dropping support for numpy1 can cause a lot of compatibility issues for people, since there are still many packages that require numpy<2 (example: [TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.20.0rc3/requirements.txt) even in its most recent release from last week).
I propose keeping `numpy>=1.26.0` for now. I did the necessary code changes to make both 1.26 and 2.xx work. Please let me know if you have concerns or any suggestions regarding my changes.
=> Bring back compatibility with numpy1

TTS/server/server.py, docs/source/server.md
-Add openai-compatible v1/audio/speech endpoint to server.py
-Add lowvram command line argument to server.py (if running in cuda, switches model to cpu when idle)
-Allow openai server to use built in speaker voices, cloning wavs or directory with wavs as the voice
-Allow language_id as server.py command line argument in alternative to request parameter
-split long input text using built in segmenter (eg to get around hard input limits in xtts2)
-tested on windows only (I do not have mac or linux)
-tested with xtts2 but changes in theory should not impact other models
=> feat(server): add OpenAI-compatible endpoint

TTS/__init__.py, TTS/tts/layers/bark/load_model.py, TTS/tts/layers/bark/model.py, TTS/tts/layers/bark/model_fine.py, TTS/tts/layers/tortoise/autoregressive.py, TTS/tts/layers/xtts/gpt.py, TTS/tts/layers/xtts/gpt_inference.py, TTS/tts/layers/xtts/stream_generator.py, TTS/tts/models/xtts.py, docs/source/faq.md, docs/source/models/xtts.md, docs/source/training/training_a_model.md, pyproject.toml
- adapt to HF changes that moved a lot of code from generate() into separate helper methods, so we don't need to duplicate that code in stream_generator.py anymore and can just call these methods
- remove some obsolete code to fall back to official HF implementations that have e.g. improved caching support
- remove branches like beam-search in xtts/stream_generator.py that are never used to shorten that code
- minimum `transformers` version increased to 4.52
Fixes #400
=> fix: update XTTS/Tortoise GPT code for HF transformers 4.52+

TTS/tts/datasets/__init__.py, TTS/tts/datasets/formatters.py, docs/source/datasets/formatting_your_dataset.md, tests/data_tests/test_dataset_formatters.py, tests/data_tests/test_loader.py
Adding a method for setting new formatter into the native formatter handling. This does not change how the existing solutions work, and thus should not cause any backwards compatibility issue. But also allows user to implement multiple custom formatters and allows using them in datasets according to their name just like the builtin formatters.  This solves both problems from the issue #290 as the the custom formatter is handled just like builtin ones.
_Adding_:
- New method for adding custom formatters
- Updating the documentation about the custom formatter using
_Testing_:
- Manually tested with multiple datasets in YourTTS model training. Works with both compute embeddings and dataset loader.
_ToDo_:
Fixes #290
=> Add new method for custom formatter handling
